config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'greetings/index'
  end

  scope "(:locale)" do
    resources :greetings, only: [:index, :create]
    root 'greetings#index'
    namespace :admin do
      get '/', :to => 'home#index'
      resources :greetings do
        get 'enable'
      end
    end
    devise_for :admin_users, path: :admin, controllers: { sessions: 'admin/devise/sessions', registrations: 'admin/devise/registrations', passwords: 'admin/devise/passwords' }
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/greeting.rb
class Greeting < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validate  :image_valid?, :if => Proc.new{ |greeting| greeting.image_changed? && greeting.errors[:image].blank? }

  def image_valid?
    white_list_content_types = ["image/jpg", "image/jpeg", "image/png", "image/x-citrix-png", "image/x-citrix-jpeg", "image/x-png", "image/pjpeg"]
    unless white_list_content_types.include?(image.file.content_type)
      errors.add(:image, I18n.t("activerecord.errors.models.greeting.attributes.image.illegal_file_attachment"))
    end
  end

  validates :name, presence: true
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout "admin/layouts/application"
  
  before_action :authenticate_admin_user!
end

app/controllers/admin/greetings_controller.rb
class Admin::GreetingsController < Admin::AdminController
  before_action :set_greetings, only: [:index]
  before_action :get_greeting, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @greeting = Greeting.new
  end

  def edit
  end

  def create
    @greeting = Greeting.new(greeting_params)
    if @greeting.save
        flash[:success] = "Created profile."
        redirect_to admin_greetings_path
    else
        render :new
    end
  end

  def update
    if @greeting.update_attributes(greeting_params)
      flash[:success] = "Updated profile."
      redirect_to admin_greetings_path
    else
      render :edit
    end
  end

  def destroy
    if @greeting.destroy
        flash[:success] = "Deleted profile."
        redirect_to admin_greetings_path
    else
        render :index
    end
  end

  def enable
    greeting = Greeting.find(params[:greeting_id])
    if greeting.update(is_enable: greeting.is_enable? ? false : true)
        render layout: false, status: :ok
    else
        render layout: false, json: "no data"
    end
  end

  private

  def set_greetings
    @greetings = Greeting.all.order("created_at").page(params[:page]).per(5)
  end

  def get_greeting
    @greeting = Greeting.find(params[:id])
  end

  def greeting_params
    params.require(:greeting).permit(:name, :comment, :is_enable, :image, :image_cache)
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::AdminController
  def index
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  layout "admin/layouts/application"

  # Admin画面のログイン -> Adminホーム画面へリダイレクト
  def after_sign_in_path_for(resource)
    admin_path
  end

  # Admin画面のログアウト -> ログイン画面へリダイレクト
  def after_sign_out_path_for(resource)
    admin_user_session_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def self.default_url_options
    { locale: I18n.locale }
  end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  before_action :set_greetings, only: [:index, :create]

  def index
    @greeting = Greeting.new
  end

  def create
    @greeting = Greeting.new(greeting_params)

    respond_to do |format|
      if @greeting.save
        flash[:info] = 'Success'
        format.html { redirect_to greetings_path }
      else
        format.html { render action: 'index' }
      end
    end
  end

  private
  def set_greetings
    @greetings = Greeting.all.order("created_at DESC").page(params[:page]).per(5)
  end

  def greeting_params
    params.require(:greeting).permit(:name, :comment)
  end
end

app/helpers/admin/greetings_helper.rb
module Admin::GreetingsHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    messages = resource.errors.full_messages.each do |errmsg|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        <small>#{errmsg}</small>
      </div>
      EOF
    end
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/views/admin/greetings/_greeting.html.slim
  section class="content"
    = bootstrap_form_for([:admin, greeting], html: {class: 'form'}) do |f|
      .form-group
        = f.text_field :id, disabled: true, readonly: true, class: "form-control"
      .form-group
        = f.text_field :name, class: "form-control"
      .form-group
        = f.text_field :comment, class: "form-control"
      .form-group
        = image_tag @greeting.image.url if @greeting.image? && @greeting.errors[:image].blank?
        = f.file_field :image, class: "form-control"
        = f.hidden_field :image_cache if @greeting.errors[:image].blank?
      = f.submit "submit", class: "btn btn-primary"

app/views/admin/greetings/edit.html.slim
section class="content-header"
  h1 Greetings::update
  = render @greeting

app/views/admin/greetings/index.html.slim
section class="content-header"
  - flash.each do |type, msg|
    div class="alert alert-#{type} alert-dismissible"
      button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times;
      h4
        i class="icon fa fa-check"
        | #{msg}
  h1 Greetings
  section class="content"
    .row
      .col-xs-12
        .box
          .box-header
            h3.box-title
              | List
          .box-body.table-responsive.o-padding
            table.table.table-hover.table-bordered
              thead
              tr
                  th
                    | id
                  th
                    | 名前
                  th
                    | コメント
                  th
                    | 作成日
                  th
                  th
              tbody
                - @greetings.each do |g|
                  tr
                    td
                      = g.id
                    td
                      = g.name
                    td
                      = g.comment
                    td
                      = g.created_at
                    td.text-center.a_area
                      = link_to "詳細", admin_greeting_path(id: g.id), class: "btn btn-block btn-default text-center"
                    td.text-center.a_area
                      button id="change_enable_#{g.id}" class="change_enable btn btn-block btn-default text-center"
                        = g.is_enable? ? "非公開" : "公開"
                      input type="hidden" value="#{g.id}"
                    td.text-center.a_area
                      = link_to "削除", admin_greeting_path(id: g.id), method: :delete, class: "btn btn-block btn-danger text-center"
            = paginate @greetings

app/views/admin/greetings/new.html.slim
section class="content-header"
  h1 Greetings::new
  = render @greeting

app/views/admin/greetings/show.html.slim
section class="content-header"
  h1 Greetings::show
  section class="content"
    = form_for ([:admin, @greeting]), html: {class: 'form'} do |f|
      .form-group
        = f.label :id
        = f.text_field :id, disabled: true, readonly: true, class: "form-control"
      .form-group
        = f.label :name
        = f.text_field :name, disabled: true, readonly: true, class: "form-control"
      .form-group
        = f.label :comment
        = f.text_field :comment, disabled: true, readonly: true, class: "form-control"
      .form-group
        = image_tag @greeting.image.url
      = link_to "編集", edit_admin_greeting_path, class: "btn btn-primary"

app/views/admin/home/index.html.slim
section class="content-header"
  h1 Dashboard
  section class="content"
    p Find me in app/views/admin/home/index.html.slim
    p ここがダッシュボードでいろいろ見れたりします。

app/views/admin/layouts/application.html.slim
doctype html
html
  head
    title
      | Admin - GuestbookSample
    = stylesheet_link_tag    'admin/application', media: 'all'
    = javascript_include_tag 'admin/application'
    = csrf_meta_tags
  body class="hold-transition skin-blue sidebar-mini"
    .wrapper
      header class="main-header"
        a> href="#{admin_path}" class="logo"
          span class="logo-mini"
            | GB
          span class="logo-lg"
            | Guestbook

        nav class="navbar navbar-static-top" role="navigation"
          a> href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"
            span class="sr-only"
              | Toggle navigation
          .navbar-custom-menu
            ul class="nav navbar-nav"
              li class="dropdown user user-menu"
                a> href="#" class="dropdown-toggle" data-toggle="dropdown"
                  span class="hidden-xs" = current_admin_user.email
                ul class="dropdown-menu"
                  li class="user-header"
                    p
                      | Test Taro - Web Developer
                      small 登録日：#{current_admin_user.created_at.strftime("%Y年%m月%d日")}
                  li class="user-footer"
                    .pull-left
                      a> href="#" class="btn btn-default btn-flat" Profile
                    .pull-right
                      = link_to "Sign out", destroy_admin_user_session_path, method: :delete, class: "btn btn-default btn-flat"
      aside class="main-sidebar"
        section class="sidebar"
          ul class="sidebar-menu"
            li class="header" Sidebar
            li class="treeview"
              a> href="#"
                i class="fa fa-table"
                span Greetings
                i class="fa fa-angle-left pull-right"
              ul class="treeview-menu"
                li
                  = link_to new_admin_greeting_path
                    i class="fa fa-circle-o"
                    | New
                li
                  = link_to admin_greetings_path
                    i class="fa fa-circle-o"
                    | List
      .content-wrapper
        = yield
      footer class="main-footer"
        strong Copyright &copy; 2016 Company. All rights reserved.

app/views/admin/layouts/login.html.slim
doctype html
html
  head
    title
      | Admin - GuestbookSample
    = stylesheet_link_tag    'admin/application', media: 'all'
    = javascript_include_tag 'admin/application'
    = csrf_meta_tags
  body class="hold-transition login-page"
    = yield

app/views/greetings/_form.html.slim
= bootstrap_form_for(@greeting, html: {class: 'form'}) do |f|
  .form-group
    = f.text_field :name, class: "form-control"
  .form-group
    = f.text_field :comment, class: "form-control"
  = f.submit "submit", class: "btn btn-primary"

app/views/greetings/index.html.slim
h1
  | Greetings
= render 'form'
hr
table.table.table-hover
  tbody
    - @greetings.each do |g|
      tr
        td.active[width="30%"]
          = g.name
          br
          small.text-muted
            = g.created_at
        td
          = g.comment
= paginate @greetings

app/views/layouts/admin.html.slim
doctype html
html
  head
    title
      | Admin - GuestbookSample
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | GuestbookSample
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .container
      = yield

app/views/maintenance/maintenance.html.erb
メンテナンス中です。